### ISSUE TITLE
README有误

### ISSUE THREAD

**Issue by Naville** [lanvsblue/LANRevealLoader#1]
README中描述RevealServer是静态库。而只要简单的在可执行文件上运行一次file即可得到完全不同的结论: 

```
λ : >>> file Reveal2Server 
Reveal2Server: Mach-O universal binary with 2 architectures: [arm_v7:Mach-O dynamically linked shared library arm_v7] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
Reveal2Server (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Reveal2Server (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by Naville** [comment]
``Loader与Server分开的好处显而易见，不同的Reveal版本只要替换不同的RevealServer就可以了，而不需要再次编译生成类似于libReveal.dylib动态库。``
RevealLoader也不需要. RevealLoader是在安装脚本里搜索下载当前最新版本的动态库并存放。本质上和你的这个事先没有区别

**Comment by lanvsblue** [comment]
感谢张总指正，学习了。就是有个疑问，为什么RevealServer改名为RevealServer.dylib后放入DynamicLibraries目录中，这个方法在iOS11中失效了呢？

**Comment by Naville** [comment]
无责任猜想iOS11的越狱没patch干净。

**Comment by lanvsblue** [comment]
已修改 README
